version: "3"
services:
  fe-react:
    container_name: fe-react
    ports:
      - "3003:80"
    build: ./frontend/dist

  be-nodejs:
    container_name: be-nodejs
    ports:
      - "8800:8800"
    build: ./API